INSERT INTO Categories (categoryName) VALUES 
('Food'),
('Education'),
('Entertainment'),
('Groceries'),
('Health'),
('Home'),
('Shopping'),
('SuperContributions'),
('TaxPaid'),
('Transport'),
('Travel'),
('Transfers'),
('Utilities'),
('Uncategorised');
